### ISSUE TITLE
image not processed

### ISSUE THREAD

**Issue by leosongwei** [PKU-YuanGroup/MoE-LLaVA#11]
When running `deepspeed --include localhost:0 predict.py`, got the error, it seems passing the image path to the part expecting loaded image:

```
Traceback (most recent call last):
  File "models_path/models/PKU_MoE/MoE-LLaVA/predict.py", line 49, in <module>
    main()
  File "models_path/models/PKU_MoE/MoE-LLaVA/predict.py", line 22, in main
    image_tensor = image_processor.preprocess(image, return_tensors='pt')['pixel_values'].to(model.device, dtype=torch.float16)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models_path/.venv/lib/python3.11/site-packages/transformers/models/siglip/image_processing_siglip.py", line 174, in preprocess
    images = make_list_of_images(images)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models_path/.venv/lib/python3.11/site-packages/transformers/image_utils.py", line 162, in make_list_of_images
    raise ValueError(
ValueError: Invalid image type. Expected either PIL.Image.Image, numpy.ndarray, torch.Tensor, tf.Tensor or jax.ndarray, but got <class 'str'>.
[2024-02-01 13:29:06,242] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 119765
```

**Comment by LinB203** [comment]
Sorry, we have fixed it.

```
image_tensor = image_processor.preprocess(Image.open(image).convert('RGB'), return_tensors='pt')['pixel_values'].to(model.device, dtype=torch.float16)
```
